### ISSUE TITLE
Class "NumberFormatter" not found

### ISSUE THREAD

**Issue by ibjshaban** [kamgrzeski/SoftCRM#33]
Error
Class "NumberFormatter" not found (View: SoftCRM\resources\views\index.blade.php)
I have edit the php.ini file `extension=php_intl.dll`, but this problem still exists.

**Comment by KamilGrzechulski** [comment]
> Error Class "NumberFormatter" not found (View: SoftCRM\resources\views\index.blade.php) I have edit the php.ini file `extension=php_intl.dll`, but this problem still exists.

Hello @ibjshaban I don't use the NumberFormatter class anywhere. Could you reainstall project?
