### ISSUE TITLE
Error in seeding

### ISSUE THREAD

**Issue by batoolfatima2135** [kamgrzeski/SoftCRM#36]
hey i ran command:
 php artisan process-softcrm 
but it gives me error in seeding of fakertaskseeder
Kindly help me out ASAP
![error](https://user-images.githubusercontent.com/61277612/158760248-c43f2fcf-5afd-44c8-a739-8b1e375b4612.png)

**Comment by KamilGrzechulski** [comment]
@batoolfatima2135 sorry for long time. Please refresh db and run seeder again.
