### ISSUE TITLE
Issue for "TypeError: Return value must be of type string, null returned" in CRM Project

### ISSUE THREAD

**Issue by diusazzad** [kamgrzeski/SoftCRM#38]
Issue Description:

I encountered a TypeError in the CRM project when using the SettingsService::loadSettingValue method. The error message states: "Return value must be of type string, null returned." This issue appears to originate from the SettingsService.php file at line 23.
TypeError
App\Services\SettingsService::loadSettingValue(): Return value must be of type string, null returned

Steps to Reproduce:

Access the CRM application.
Navigate to the specific scenario where the loadSettingValue method is being used.
Observe the error message mentioned above.

C:\xampp\htdocs\Fork\SoftCRM\app\Services\SettingsService.php:23

private SettingsModel $settingsModel;

public function __construct()
{
    $this->settingsModel = new SettingsModel();
}

public function loadSettingValue(string $key) : string
{
    return $this->settingsModel->getSettingValue($key);
}

Possible Solution:

Inspect the logic within the getSettingValue method in the SettingsModel class. If the method is expected to return a string but is returning null, investigate why the value is not being retrieved properly from the database.

**Comment by kamgrzeski** [comment]
@diusazzad fixed in branch master.
